name: Release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    name: Build and Create Tagged Release
    runs-on: ubuntu-latest
    steps:
      - name: Install archive tools
        run: sudo apt install zip

      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 8.6.1

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 22.x
          cache: 'pnpm'
          cache-dependency-path: 'web/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install
        working-directory: web

      - name: Install package dependencies
        run: pnpm install
        working-directory: web

      - name: Run build
        run: pnpm build
        working-directory: web
        env:
          CI: false

      - name: Bump manifest version
        id: bump_version
        run: |
          node .github/actions/bump-manifest-version.js
          # Get the new version from fxmanifest.lua
          NEW_VERSION=$(grep -oP "version\s+'(\K[\d.]+)(?=')" fxmanifest.lua)
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
        env:
          TGT_RELEASE_VERSION: ${{ github.ref_name }}

      - name: Push manifest change
        uses: EndBug/add-and-commit@v8
        with:
          add: fxmanifest.lua
          push: true
          author_name: Manifest Bumper
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'chore: bump manifest version to ${{ env.NEW_VERSION }}'

      - name: Update branch
        working-directory: ./ 
        run: git push origin HEAD:main

      - name: Bundle files
        run: |
          mkdir -p ./temp/dirk_reactBoilerplate
          mkdir -p ./temp/dirk_reactBoilerplate/web/
          cp ./fxmanifest.lua ./temp/dirk_reactBoilerplate/
          cp ./README.md ./temp/dirk_reactBoilerplate/
          cp -r ./src ./temp/dirk_reactBoilerplate
          cp -r ./locales ./temp/dirk_reactBoilerplate
          cp -r ./settings ./temp/dirk_reactBoilerplate
          cp -r ./web/build ./temp/dirk_reactBoilerplate/web/
          cd ./temp && zip -r ../dirk_reactBoilerplate.zip ./dirk_reactBoilerplate

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        id: auto_release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          title: "Release ${{ env.NEW_VERSION }}"  # Use the bumped version number here
          prerelease: false
          files: dirk_reactBoilerplate.zip
          automatic_release_tag: 'latest_production'
        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
